### ISSUE TITLE
libgstreamer rpi dependency version

### ISSUE THREAD

**Issue by tntclaus** [chschnell/build-qt5-rpi#3]
Hi, thank you for this really good work. 

I'm a bit curious is there any important reason why you include `libgstreamer0.10-dev` and `libgstreamer-plugins-base0.10-dev` at the times when there are gst-1.0 packages available?

**Comment by chschnell** [comment]
Thanks, and you're welcome!

The two libgstreamer pacakges needed to be 0.10 for qt 5.9.3. That might have changed with qt 5.9,4, do you know more about it?

**Comment by tntclaus** [comment]
Afaik Qt >= 5.8 should rely on gst-1.0 by default. And according to [this thread](https://forum.qt.io/topic/67338/qtmultimedia-work-with-gstreamer-1-0/12) you can specify the version explicitly for QtMultimedia with:
```
qmake -r GST_VERSION=1.0
make
make install
```

I am currently stuck with weird gstreamer behaviour on RPi3. `gst-play-1.0` perfectly decodes Full HD mp4 videos using playbin, `qopenglwidget` and `cube` examples definetely utilize `brcm_egls`. But if you will try to make them work together you get fucked with terrrible framedrops (while logs show that hardware decoding is utilezed) :) 

I'm not asking for help, but any ideas are appreciated :)

**Comment by tntclaus** [comment]
Ok, actually there is no need to explicitly set  GST_VERSION=1.0. Qt determines available version of gstreamer and configures itself to use it. Just checked it is working.

I suggest update gstreamer dependency to 1.0. (though it is really broken on Stretch, for compiling and linking purposes it should not be a problem).

**Comment by chschnell** [comment]
Please try the new release I just committed.

Since they do not conflict I am simply installing both glstreamer 0.10 and 1.0 now and let the Qt builder pick the one it prefers (Qt 5.9.4 in my case chooses 1.0).

Cheers and let me know if it works!
Christian

**Comment by tntclaus** [comment]
I tested previous version with gst-1.0 and it's working. Thanks!

**Comment by chschnell** [comment]
Great, and thanks for the feedback!
