### ISSUE TITLE
ERROR: The OpenGL functionality tests failed! 

### ISSUE THREAD

**Issue by ggillesa69** [chschnell/build-qt5-rpi#6]
Linux rasp 4.14.93-v7+ #1191 SMP Wed Jan 16 11:53:33 GMT 2019 armv7l GNU/Linux
i get message when i run  ./configure -developer-build -opensource on Raspberry Pi 3
......
Note: Also available for Linux: linux-clang linux-icc

Note: Disabling X11 Accessibility Bridge: D-Bus or AT-SPI is missing.

Note: No wayland-egl support detected. Cross-toolkit compatibility disabled.

WARNING: gperf is required to build QtWebEngine.

WARNING: bison is required to build QtWebEngine.

WARNING: flex is required to build QtWebEngine.

ERROR: The OpenGL functionality tests failed!
You might need to modify the include and library search paths by editing QMAKE_INCDIR_OPENGL[_ES2],
QMAKE_LIBDIR_OPENGL[_ES2] and QMAKE_LIBS_OPENGL[_ES2] in the mkspec for your platform.

I enable  GL Driver with raspi-config ( G1 GL  (Full KMS)...but i get the message above..
i can't figure it out...
thanks

**Comment by chschnell** [comment]
gperf, bison and flex should have been installed in this step: https://github.com/chschnell/build-qt5-rpi#debian-setup

Please follow the instructions in the readme closely, maybe you missed this step.
