### ISSUE TITLE
Creating qmake failed////

### ISSUE THREAD

**Issue by ggillesa69** [chschnell/build-qt5-rpi#7]

**Comment by ggillesa69** [comment]
I corrected mistake during config process of build-qt5-rpi.sh.
Because of qt-everywhere-src-5.12.0/configure was "ASCII text, with CRLF line terminators" format,
The creation of qmake is failed. I convert  file in unix format and i figure it out. ( dos2unix command )
but now the 'creating qmake' process  is failed ...

i run ../build-qt5-rpi/build-qt5-rpi.sh config and i get fellowing message....

root@myhost:/tmp/qt5.12.0# ../build-qt5-rpi/build-qt5-rpi.sh config
[build-qt5-rpi 00:00:00] Qt5 cross-builder for Raspberry Pi
[build-qt5-rpi 00:00:00] config: starting
[build-qt5-rpi.sh:553] clean_host
[build-qt5-rpi 00:00:00] Cleaning host files from previous build
[build-qt5-rpi.sh:254] sudo rm -rf /tmp/qt5.12.0/build /usr/local/qt5-rpi /usr/local/qt5
[build-qt5-rpi.sh:554] configure_qt
[build-qt5-rpi 00:00:00] Running Qt's configure
[build-qt5-rpi.sh:259] mkdir -p /tmp/qt5.12.0 /tmp/qt5.12.0/build
[build-qt5-rpi.sh:260] pushd /tmp/qt5.12.0/build
/tmp/qt5.12.0/build /tmp/qt5.12.0
[build-qt5-rpi.sh:261] /tmp/qt-everywhere-src-5.12.0/configure -release -opensource -confirm-license -platform linux-g++ -device linux-rasp-pi2-g++ -device-option CROSS_COMPILE=arm-linux-gnueabihf- -opengl es2 -silent -nomake tests -nomake examples -sysroot /usr/local/qt5-rpi-sysroot -prefix /usr/local/qt5-rpi -extprefix /usr/local/qt5-rpi -hostprefix /usr/local/qt5
+ cd qtbase
+ /tmp/qt-everywhere-src-5.12.0/qtbase/configure -top-level -release -opensource -confirm-license -platform linux-g++ -device linux-rasp-pi2-g++ -device-option CROSS_COMPILE=arm-linux-gnueabihf- -opengl es2 -silent -nomake tests -nomake examples -sysroot /usr/local/qt5-rpi-sysroot -prefix /usr/local/qt5-rpi -extprefix /usr/local/qt5-rpi -hostprefix /usr/local/qt5
Preparing build tree...
Creating qmake...
g++: error: unrecognized debug output level ‘\x0d’
’; did you mean ‘-fdata-sections’?
make: *** [main.o] Error 1
.[[build-qt5-rpi.sh:261] exit
[build-qt5-rpi.sh:1] exit_handler

[build-qt5-rpi 00:00:00] *** Build failed
--------------------------------------------------------------
anybody could help me ??
thanks

**Comment by chschnell** [comment]
I have not tested qt5.12.0 yet, last I checked was qt5.10.1.

However the qt sources for linux certainly do not have DOS line endings <CR><LF>. Please download the .tar.xz (I believe you fetched the .zip) at

https://download.qt.io/archive/qt/5.12/5.12.0/single/qt-everywhere-src-5.12.0.tar.xz

Note that I am building qt5.12.0 right now, this will take a couple of hours. I am already passed the "config" step, I am running "build" right now, so it should work for you as well. I have not tested qt5.12.0 before, I believe that build-qt5-rpi is rather likely to fail without modifications. So I don't recommend it (yet).

Again please follow the instructions for the build script as closely as possible. Start with a working configuration (that would have been qt.5.9.4 and Raspbian 2018-04-18) and work your way up from there. I will update my build script to more recent releases in the near future, but there can be tons of issues.

Good luck!

**Comment by chschnell** [comment]
Ok, don't use qt5.12.0, qtwebengine fails complaining that if cannot find X11/Xlib-xcb.h, I am not sure I can fulfill this dependency without pulling in all the other X11 stuff. This will need more time than I currently have, Please use qt5.9. Thanks.

**Comment by ggillesa69** [comment]
ok, i get back to qt5.10.0, it seems to be the best way... thanks

**Comment by chschnell** [comment]
Ok. I will look into qt5.11 and qt5.12 in the next couple of weeks, if it works I will then update this site.
