### ISSUE TITLE
Fails with Debian 9.7 and qt5.10.0

### ISSUE THREAD

**Issue by ggillesa69** [chschnell/build-qt5-rpi#8]
Hi,
i got the fellowing message  : 
/usr/bin/ld.gold: warning: skipping incompatible /usr/local/qt5-rpi-sysroot/usr/lib/arm-linux-gnueabihf/libpthread.so while searching for pthread
/usr/bin/ld.gold: fatal error: /usr/local/qt5-rpi-sysroot/usr/lib/arm-linux-gnueabihf/libdl.so: unsupported ELF machine number 40
collect2: error: ld returned 1 exit status
[2/10667] CXX host/obj/third_party/protobuf/protobuf_full/coded_stream.o
ninja: build stopped: subcommand failed.
Makefile.gn_run:1027 : la recette pour la cible « run_ninja » a échouée
make[4]: *** [run_ninja] Erreur 1
make[4] : on quitte le répertoire « /root/qt5.10.0/build/qtwebengine/src/core »
Makefile:80 : la recette pour la cible « sub-gn_run-pro-make_first » a échouée
make[3]: *** [sub-gn_run-pro-make_first] Erreur 2
make[3] : on quitte le répertoire « /root/qt5.10.0/build/qtwebengine/src/core »
Makefile:77 : la recette pour la cible « sub-core-make_first » a échouée
make[2]: *** [sub-core-make_first] Erreur 2
make[2] : on quitte le répertoire « /root/qt5.10.0/build/qtwebengine/src »
Makefile:46 : la recette pour la cible « sub-src-make_first » a échouée
make[1]: *** [sub-src-make_first] Erreur 2
make[1] : on quitte le répertoire « /root/qt5.10.0/build/qtwebengine »
Makefile:1027 : la recette pour la cible « module-qtwebengine-make_first » a échouée
make: *** [module-qtwebengine-make_first] Erreur 2
make : on quitte le répertoire « /root/qt5.10.0/build »
[[build-qt5-rpi.sh:267] exit
[build-qt5-rpi.sh:1] exit_handler

[build-qt5-rpi 00:01:18] *** Build failed

does anybody can help me ?
excuse me for the french notes..
thanks

**Comment by chschnell** [comment]
It is a bug in Qt's build script. the native linker is trying to link arm library libddl.so.

Please use Qt5.9, this build script does not support Qt10 yet, and I am not sure if I will ever add support for Qt10 (it's quite a bit more bloat).
