### ISSUE TITLE
how integrate deb package with qtcreator

### ISSUE THREAD

**Issue by ggillesa69** [chschnell/build-qt5-rpi#9]
Everything is fine in may case... I created 2 deb packages qt-everywhere-opensource-host_5.9.4_amd64.deb and qt-everywhere-opensource-rpi_5.9.4_armhf.deb.
I'd like to integrade the amd package in qtcreator. how can i do ?

thanks

**Comment by chschnell** [comment]
I believe all you need to do is point Qt Creator to the qmake executable which is packed with qt-everywhere-opensource-host_5.9.4_amd64.deb. I think you should find instructions here: https://doc.qt.io/qtcreator/creator-build-settings.html
